name: linux

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/linux.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/linux.yml'

env:
  CMAKE_BUILD_TYPE: 'Release'
  CC: clang
  CXX: clang++

jobs:
  build_client:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_linux_deps clang-11

      - name: Build Client
        run: |
          ./util/ci/build.sh
        env:
          CMAKE_FLAGS: "-DBUILD_CLIENT=1 -DENABLE_PROMETHEUS=0 -DENABLE_CURSES=0"

      - name: Package Client artifacts
        run: |
          mkdir -p artifacts
          cp -r ./bin/luanti artifacts/
          cd artifacts
          zip -r client.zip luanti
          
      - name: Upload Client artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-artifacts
          path: artifacts/*

  build_server:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_linux_deps clang-11

      - name: Build Server
        run: |
          ./util/ci/build.sh
        env:
          CMAKE_FLAGS: "-DBUILD_SERVER=1 -DENABLE_PROMETHEUS=0 -DENABLE_CURSES=0"

      - name: Package Server artifacts
        run: |
          mkdir -p artifacts
          cp -r ./bin/luantiserver artifacts/
          cd artifacts
          
          
      - name: Upload Server artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server-artifacts
          path: artifacts/*
